<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Potok.SearchEngine.Tests</RootNamespace>
        <AssemblyName>Potok.SearchEngine.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Potok.SearchEngine.Core\Potok.SearchEngine.Core.csproj" />
        <ProjectReference Include="..\..\src\Potok.SearchEngine.Infrastructure\Potok.SearchEngine.Infrastructure.csproj" />
        <ProjectReference Include="..\..\src\Potok.SearchEngine\Potok.SearchEngine.csproj" />
    </ItemGroup>

</Project>
